import archiver from 'archiver';
import { Readable } from 'stream';
import { MARKETPLACE_SPECS } from '../utils/constants';

/**
 * Create ZIP file with marketplace-organized folders
 * 
 * @param {Object} productData - Product data with processed images
 * @param {string} productName - Product name for ZIP filename
 * @returns {Promise<Buffer>} - ZIP file buffer
 */
export async function createProductZip(productData, productName) {
  return new Promise((resolve, reject) => {
    try {
      // Create archiver instance
      const archive = archiver('zip', {
        zlib: { level: 9 }, // Maximum compression
      });
      
      const chunks = [];
      
      // Collect data chunks
      archive.on('data', (chunk) => {
        chunks.push(chunk);
      });
      
      // Handle completion
      archive.on('end', () => {
        const buffer = Buffer.concat(chunks);
        resolve(buffer);
      });
      
      // Handle errors
      archive.on('error', (err) => {
        reject(err);
      });
      
      // Add files for each marketplace
      productData.marketplaces.forEach((marketplace) => {
        const folderName = marketplace;
        
        // Add main image
        if (productData.processedImages[marketplace]?.main) {
          archive.append(
            productData.processedImages[marketplace].main,
            { name: `${folderName}/main_${getMarketplaceSize(marketplace)}.jpg` }
          );
        }
        
        // Add secondary images
        if (productData.processedImages[marketplace]?.secondary) {
          productData.processedImages[marketplace].secondary.forEach((img, index) => {
            archive.append(
              img.buffer,
              { name: `${folderName}/image_${index + 2}_${getMarketplaceSize(marketplace)}.jpg` }
            );
          });
        }
        
        // Add thumbnail for Shopify
        if (marketplace === 'Shopify' && productData.processedImages[marketplace]?.thumbnail) {
          archive.append(
            productData.processedImages[marketplace].thumbnail,
            { name: `${folderName}/thumb_600x600.jpg` }
          );
        }
        
        // Add upload guide PDF
        const uploadGuide = generateUploadGuidePDF(marketplace, productData);
        archive.append(
          uploadGuide,
          { name: `${folderName}/UPLOAD_GUIDE.txt` }
        );
      });
      
      // Finalize the archive
      archive.finalize();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Get marketplace image size as string
 * 
 * @param {string} marketplace - Marketplace name
 * @returns {string} - Size string (e.g., "2000x2000")
 */
function getMarketplaceSize(marketplace) {
  const specs = MARKETPLACE_SPECS[marketplace];
  if (!specs) return '2000x2000';
  
  const [width, height] = specs.mainImage.size;
  return `${width}x${height}`;
}

/**
 * Generate upload guide text file for each marketplace
 * 
 * @param {string} marketplace - Marketplace name
 * @param {Object} productData - Product data
 * @returns {Buffer} - Upload guide content
 */
function generateUploadGuidePDF(marketplace, productData) {
  const specs = MARKETPLACE_SPECS[marketplace];
  const [width, height] = specs.mainImage.size;
  
  let guide = `
═══════════════════════════════════════
${marketplace.toUpperCase()} - UPLOAD GUIDE
Generated by PicPolish
═══════════════════════════════════════

UPLOAD ORDER (IMPORTANT):

1️⃣  MAIN IMAGE: main_${width}x${height}.jpg
   Upload as: Primary Product Image
   This is your listing thumbnail

`;
  
  // Add secondary images
  const secondaryCount = productData.processedImages[marketplace]?.secondary?.length || 0;
  for (let i = 0; i < secondaryCount; i++) {
    const imageType = productData.secondaryImageTypes?.[i] || 'Info';
    guide += `${i + 2}️⃣  IMAGE ${i + 2}: image_${i + 2}_${width}x${height}.jpg (${imageType})
   Upload as: Alternate View ${i + 1}

`;
  }
  
  // Add thumbnail for Shopify
  if (marketplace === 'Shopify') {
    guide += `
📸 THUMBNAIL: thumb_600x600.jpg
   Upload as: Product thumbnail
`;
  }
  
  // Add compliance checklist
  guide += `
✅ ALL IMAGES ARE ${marketplace.toUpperCase()}-COMPLIANT:
   - Pure white background (RGB 255,255,255) ✓
   - ${width} x ${height} pixels ✓
   - 85% product coverage ✓
   - No text/watermarks on main image ✓

⚠️  IMPORTANT NOTES:
   - Upload main image FIRST
   - Secondary images can be in any order
   - Do not edit these images before upload
   - They are already optimized for ${marketplace}

Need help? support@picpolish.com
═══════════════════════════════════════
`;
  
  return Buffer.from(guide, 'utf-8');
}

/**
 * Create simple ZIP with array of files
 * 
 * @param {Array<Object>} files - Array of {name, buffer} objects
 * @param {string} zipName - ZIP filename
 * @returns {Promise<Buffer>} - ZIP buffer
 */
export async function createSimpleZip(files) {
  return new Promise((resolve, reject) => {
    try {
      const archive = archiver('zip', {
        zlib: { level: 9 },
      });
      
      const chunks = [];
      
      archive.on('data', (chunk) => chunks.push(chunk));
      archive.on('end', () => resolve(Buffer.concat(chunks)));
      archive.on('error', (err) => reject(err));
      
      // Add each file
      files.forEach(({ name, buffer }) => {
        archive.append(buffer, { name });
      });
      
      archive.finalize();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Extract files from ZIP (if needed for processing)
 * Note: For browser-side, use JSZip instead
 * 
 * @param {Buffer} zipBuffer - ZIP file buffer
 * @returns {Promise<Array<Object>>} - Extracted files
 */
export async function extractZip(zipBuffer) {
  // This would require 'unzipper' or similar library
  // For MVP, we don't need ZIP extraction on server
  // If needed later, install: npm install unzipper
  throw new Error('ZIP extraction not implemented in Phase 1');
}

/**
 * Get ZIP file size estimate
 * 
 * @param {number} fileCount - Number of files
 * @param {number} avgFileSize - Average file size in bytes
 * @returns {number} - Estimated ZIP size
 */
export function estimateZipSize(fileCount, avgFileSize) {
  // ZIP compression typically achieves 10-30% reduction for JPEG
  const compressionRatio = 0.85; // Conservative estimate
  return Math.ceil(fileCount * avgFileSize * compressionRatio);
}