import archiver from 'archiver';
import { MARKETPLACE_SPECS } from '../utils/constants';

/**
 * Create ZIP file with marketplace-organized folders
 * Windows-compatible version
 */
export async function createProductZip(productData, productName) {
  return new Promise((resolve, reject) => {
    try {
      console.log('Starting ZIP creation for:', productName);
      
      // Create archiver with Windows-compatible settings
      const archive = archiver('zip', {
        zlib: { level: 6 }, // Medium compression for compatibility
        forceZip64: false,
      });
      
      const chunks = [];
      let fileCount = 0;
      
      // Collect data chunks
      archive.on('data', (chunk) => {
        chunks.push(chunk);
      });
      
      // Handle completion
      archive.on('end', () => {
        const buffer = Buffer.concat(chunks);
        console.log('ZIP completed:', buffer.length, 'bytes,', fileCount, 'files');
        resolve(buffer);
      });
      
      // Handle warnings
      archive.on('warning', (err) => {
        if (err.code === 'ENOENT') {
          console.warn('ZIP warning:', err);
        } else {
          reject(err);
        }
      });
      
      // Handle errors
      archive.on('error', (err) => {
        console.error('ZIP error:', err);
        reject(err);
      });
      
      // Add files for each marketplace
      productData.marketplaces.forEach((marketplace) => {
        const folderName = marketplace;
        console.log('Adding files for:', marketplace);
        
        // Add main image
        if (productData.processedImages[marketplace]?.main) {
          const fileName = `${folderName}/main_${getMarketplaceSize(marketplace)}.jpg`;
          archive.append(productData.processedImages[marketplace].main, { 
            name: fileName 
          });
          fileCount++;
          console.log('Added:', fileName);
        }
        
        // Add secondary images (Phase 2)
        if (productData.processedImages[marketplace]?.secondary) {
          productData.processedImages[marketplace].secondary.forEach((img, index) => {
            const fileName = `${folderName}/image_${index + 2}_${getMarketplaceSize(marketplace)}.jpg`;
            archive.append(img.buffer, { name: fileName });
            fileCount++;
            console.log('Added:', fileName);
          });
        }
        
        // Add thumbnail for Shopify
        if (marketplace === 'Shopify' && productData.processedImages[marketplace]?.thumbnail) {
          const fileName = `${folderName}/thumb_600x600.jpg`;
          archive.append(productData.processedImages[marketplace].thumbnail, { 
            name: fileName 
          });
          fileCount++;
          console.log('Added:', fileName);
        }
        
        // Add upload guide
        const uploadGuide = generateUploadGuidePDF(marketplace, productData);
        archive.append(uploadGuide, { 
          name: `${folderName}/UPLOAD_GUIDE.txt` 
        });
        fileCount++;
        console.log('Added: UPLOAD_GUIDE.txt');
      });
      
      console.log('Finalizing ZIP with', fileCount, 'files...');
      
      // Finalize the archive
      archive.finalize();
      
    } catch (error) {
      console.error('ZIP creation error:', error);
      reject(error);
    }
  });
}

/**
 * Get marketplace image size as string
 */
function getMarketplaceSize(marketplace) {
  const specs = MARKETPLACE_SPECS[marketplace];
  if (!specs) return '2000x2000';
  
  const [width, height] = specs.mainImage.size;
  return `${width}x${height}`;
}

/**
 * Generate upload guide text file
 */
function generateUploadGuidePDF(marketplace, productData) {
  const specs = MARKETPLACE_SPECS[marketplace];
  const [width, height] = specs.mainImage.size;
  
  let guide = `
═══════════════════════════════════════
${marketplace.toUpperCase()} - UPLOAD GUIDE
Generated by PicPolish
═══════════════════════════════════════

UPLOAD ORDER (IMPORTANT):

1️⃣  MAIN IMAGE: main_${width}x${height}.jpg
   Upload as: Primary Product Image
   This is your listing thumbnail

`;
  
  // Add secondary images
  const secondaryCount = productData.processedImages[marketplace]?.secondary?.length || 0;
  for (let i = 0; i < secondaryCount; i++) {
    const imageType = productData.secondaryImageTypes?.[i] || 'Info';
    guide += `${i + 2}️⃣  IMAGE ${i + 2}: image_${i + 2}_${width}x${height}.jpg (${imageType})
   Upload as: Alternate View ${i + 1}

`;
  }
  
  // Add thumbnail for Shopify
  if (marketplace === 'Shopify') {
    guide += `
📸 THUMBNAIL: thumb_600x600.jpg
   Upload as: Product thumbnail
`;
  }
  
  // Add compliance checklist
  guide += `
✅ ALL IMAGES ARE ${marketplace.toUpperCase()}-COMPLIANT:
   - Pure white background (RGB 255,255,255) ✓
   - ${width} x ${height} pixels ✓
   - 85% product coverage ✓
   - No text/watermarks on main image ✓

⚠️  IMPORTANT NOTES:
   - Upload main image FIRST
   - Secondary images can be in any order
   - Do not edit these images before upload
   - They are already optimized for ${marketplace}

Need help? support@picpolish.com
═══════════════════════════════════════
`;
  
  return Buffer.from(guide, 'utf-8');
}

/**
 * Create simple ZIP with array of files
 */
export async function createSimpleZip(files) {
  return new Promise((resolve, reject) => {
    try {
      const archive = archiver('zip', {
        zlib: { level: 6 },
      });
      
      const chunks = [];
      
      archive.on('data', (chunk) => chunks.push(chunk));
      archive.on('end', () => resolve(Buffer.concat(chunks)));
      archive.on('error', (err) => reject(err));
      
      // Add each file
      files.forEach(({ name, buffer }) => {
        archive.append(buffer, { name });
      });
      
      archive.finalize();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Get ZIP file size estimate
 */
export function estimateZipSize(fileCount, avgFileSize) {
  const compressionRatio = 0.85;
  return Math.ceil(fileCount * avgFileSize * compressionRatio);
}